//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinalWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestauranteEntitiesContext : DbContext
    {
        public RestauranteEntitiesContext()
            : base("name=RestauranteEntitiesContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetalleBoleta> DetalleBoletas { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<ModoDePago> ModoDePagoes { get; set; }
        public virtual DbSet<Productos_Pedidos> Productos_Pedidos { get; set; }
        public virtual DbSet<TipoEmpleado> TipoEmpleadoes { get; set; }
        public virtual DbSet<TipoProducto> TipoProductoes { get; set; }
        public virtual DbSet<PP> PPS { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<DB> DBS { get; set; }
        public virtual DbSet<P> PS { get; set; }
        public virtual DbSet<Pedido> Pedidoes { get; set; }
    
        public virtual int eliminar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminar");
        }
    
        public virtual int eliminarTodo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("eliminarTodo");
        }
    }
}
